config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'
  resources :charges
  resources :purchases, only: [:show]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
	after_create :email_purchaser

	def email_purchaser
		PurchaseMailer.purchase_receipt(self).deliver
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	
	def create
	  # Amount in cents

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => params[:amount],
	    :description => 'Rails Stripe customer',
	    :currency    => 'usd'
	  )

	  purchase = Purchase.create(email: params[:stripeEmail], card: params[:stripeToken], 
	  	amount: params[:amount], description: charge.description, currency: charge.currency,
	  	customer_id: customer.id, product_id: 1)

	  redirect_to purchase

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def show
    @purchase = Purchase.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/charges/create.html.erb
Thank you for your purchase!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title>LearnRailsPayments</title>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,700,300,800">
    <title>LearnRailsPayments</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="content" class="container">
      <header id="content-header">
          <div id="price-container">
            <span class="glyphicon glyphicon-tag"></span><span class="price">$9.99</span>
          </div>
          <%= image_tag 'header-image.jpg', id:"content-head-img", alt: "Learn Rails" %>
      </header>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/purchase_mailer.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Document</title>
  </head>
  <body>
    <%= yield %>
    <p> Thanks for your purchase! </p>
  </body>
</html>

app/views/pages/home.html.erb
    <section id="content-details" class="row clearfix">
        <article id="details-article" class="col-sm-8">
            <h1 id="article-title">Your Product <span class="font-weight-light">Product Name</span></h1>
           

            <p>Lorem ipsum dolor sit amet, in nam feugiat eleifend. Sea an possit offendit definiebas, usu cu aeque mediocritatem. Vis constituam suscipiantur ad, cum duis concludaturque no. Sea vocent consulatu at.</p>

            <p>Lorem ipsum dolor sit amet, pri id tractatos torquatos, eruditi alienum eam ad. Sint graeci mel te. Ex eius corrumpit.</p>
            <p><strong>What You Get</strong></p>
            <ul class="no-indent">
                <li>Lorem ipsum dolor sit.</li>
                <li>Lorem ipsum dolor sit amet, cum.</li>
                <li>Lorem ipsum dolor sit amet, quo ne etiam.</li>
            </ul>
        </article>
        <aside id="details-aside" class="col-sm-4">
            
            <%= form_tag charges_path, id: 'chargeForm' do %>
                
                  <% if flash[:error].present? %>
                    <div id="error_explanation">
                      <p><%= flash[:error] %></p>
                    </div>
                  <% end %>
                  


                <script src="https://checkout.stripe.com/checkout.js"></script>
                <%= hidden_field_tag 'stripeToken' %>
                <%= hidden_field_tag 'amount', 499 %>
                <%= hidden_field_tag 'stripeEmail' %>
                <button id="btn-buy" type='button' class='btn btn-success btn-lg btn-block'>
                  <span class="glyphicon glyphicon-ok"></span>Buy this!
                </button>

                <script>
                    var handler = StripeCheckout.configure({
                      key: '<%= Rails.configuration.stripe[:publishable_key] %>',
                      token: function(token, arg) {
                        document.getElementById("stripeToken").value = token.id;
                        document.getElementById("stripeEmail").value = token.email;
                        document.getElementById("chargeForm").submit();
                      }
                });
                document.getElementById('btn-buy').addEventListener('click', function(e) {
                  handler.open({
                    name: 'Learn Rails',
                        description: 'Buy this item for ($4.99)',
                        amount: document.getElementById('amount').value
                    });
                    e.preventDefault();
                  })
                </script>
              <% end %>

            <ul id="details-infobox" class="list-group">
              <li class="list-group-item active clearfix">Info</li>
              <li class="list-group-item">What You Get</li>
              <li class="list-group-item">This Is Included</li>
            </ul>
        </aside>
    </section>
<footer id="site-footer">
Made by <a href="#" target="_blank"><p>Learn Rails</p></a>
</footer>

app/views/purchases/show.html.erb
<p>This is your purchase</p>
<p>Your purchase is <%= @purchase.inspect %></p>

<p>Here is 
  <a href="https://sarvar-rails-learnapp-bucket.s3.us-east-1.amazonaws.com/uzbekistan.jpeg?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEH0aCmV1LW5vcnRoLTEiRjBEAiEAiigRS5fGDJqJwbjKjgXxa9FJceqmES19UCe9eSc3jvkCHzySSt2r70Sts73sbDPNGKeKyGfGbRGhKK004sgLjWsq7QIIxv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgw4OTc3OTE4OTY5MzYiDCenjnK4fDIhvaCscCrBApH%2F%2BFdZOTAlkqXT%2Fd%2FCbZR8uef1g1egbdxkyR6hoHHQ%2B%2FU2oOUPADETaQUckrtRI5DoCKH0kjl3G5AJEldoxgEv167%2FeriY7JgANslG5LvCiUoFtZf3%2BwVnW9PkUPIMzEMSp2Ixk2C6NlGdRsoaEQOFVF%2FbR11ccsKJmEgJMlc9uncUE4hGkpCxCoSdorshrCA%2FA2Pj6V3UVKLo8k9elj5QHtkczR%2FqVWOo%2BZwlnVQ8PD7%2BLVQxLlX%2B3lWCtMDClqzXjA9fU1UPjAyEk2y6famOOAIU3kebZ3T8BnkHALwT9eLyXNAKnj3onb%2F3mKEW4N5WwR0EiqNZEIcUtvHdyycKe5SwJwwfavaHOqJzUJDyVXiy9Jo8UnIiZmnoKB%2Fb6uXmZdOpTnbhGu6Z%2B%2BTPo4Kayl7F3SgGgx7kfOo%2FXNPewjDSxLWQBjq0AqDW8YgYGzrrh4RZc8FK57CyrzqSs8p%2Bnw%2BkSTJ4%2BpCk3sbqeLXreZV6ColqK6r5cL0tIJUOqO2QxbE4sTk6GJzN0M%2BDUWG2vT2vjzsHH4BRtlZxNSNTWZBALCyWxq8G2GuqfqTQcZvwpn4VUp18VcPDvTzNGfuR%2FnpEnhCqr89hKfj7o42caYsNOS2q%2B%2FcZHjU%2B5B3oaDV13P25beSdwDuCZJoFZz8vxpZoiIHz8zWMlhfiPIvxJSHApHth%2Bez%2FFGvjOjeVLlJ2KGLxITQYG7mPtGalwKRnJFTHErVFqg4bUbqCIqVDbjTk3jRxUr%2BQMfeXNjvArzI7%2B7VNQrqJld%2FNqDwadPLzNPJu8PPgATVpyyOcPQdHEwT8lecfRK3n8%2FnfhlOMWqCVWL2WKfYtH%2BRDzFBD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220216T210755Z&X-Amz-SignedHeaders=host&X-Amz-Expires=518400&X-Amz-Credential=ASIA5CCERFVUHBP6MTMG%2F20220216%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=a6542a8187bc620126312217d9dd8ff253a891db52c07e2a883e38e6f22ba14a">
    your file
  </a>
</p>